algoritmo "aula1"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Danielle]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas Toterol
// Data atual  : 27/02/25
var

    a, b: inteiro

inicio

    a<-3 // Atribui o valor 3 a variável a
    b<-5 // Atribui o valor 5 a variável b

    escreval("A soma de ", a, " com ", b, " é: ", a+b) // Mostra a soma de a e b

fimalgoritmo 